title: Experience AI Challenge Stage 3 - Listen and Label
hero_image: images/banner.png
description: This whole stage of the quest is just about listening to music! In this stage of the ExperimentAI Music quest, you will collect data to train your machine learning model by listening to as much music as you can and classifying it with your app.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Introduction
  - title: Collect song data
  - title: Train the model with your data
  - title: What next?
